const mongoose = require("mongoose");

const MONGO_URI = "mongodb://127.0.0.1:27017/plantify-backend";

const PlantSchema = new mongoose.Schema({
  name: String,
  scientificName: String,
  family: String,
  category: String,
  description: String,
  image: String,
  careGuide: {
    water: String,
    sunlight: String,
    soil: String,
    difficulty: String,
  },
  climate: String,
  price: String,
  availability: String,
  health: String,
  diseases: [String],
  tags: [String],
});

const Plant = mongoose.model("TrefleePlant", PlantSchema);

const plants = [
  // ───── FRUITS ─────
  {
    name: "Mango",
    scientificName: "Mangifera indica",
    family: "Anacardiaceae",
    category: "Trees",
    description: "King of fruits. Large tropical tree producing sweet, juicy fruits. National tree of Pakistan and India.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Hapus_Mango.jpg/320px-Hapus_Mango.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Deep well-drained", difficulty: "Moderate" },
    climate: "Tropical",
    price: "PKR 500–2000",
    availability: "Seasonal",
    health: "Rich in vitamins A, C, B6. Boosts immunity and digestion.",
    diseases: ["Anthracnose", "Powdery Mildew", "Mango Malformation"],
    tags: ["fruit", "tropical", "shade", "national-tree"],
  },
  {
    name: "Banana",
    scientificName: "Musa acuminata",
    family: "Musaceae",
    category: "Trees",
    description: "Fast-growing tropical plant producing energy-rich fruits. One of the world's most consumed fruits.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana-Fruit-Pieces.jpg/320px-Banana-Fruit-Pieces.jpg",
    careGuide: { water: "High", sunlight: "Full Sun", soil: "Rich, moist loam", difficulty: "Easy" },
    climate: "Tropical",
    price: "PKR 100–300",
    availability: "Year-round",
    health: "High in potassium, vitamin B6, fiber. Great energy source.",
    diseases: ["Panama Disease", "Black Sigatoka", "Bunchy Top"],
    tags: ["fruit", "tropical", "indoor-pot"],
  },
  {
    name: "Apple",
    scientificName: "Malus domestica",
    family: "Rosaceae",
    category: "Trees",
    description: "Deciduous fruit tree producing crisp, sweet-tart fruits. Thrives in cool temperate climates.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Red_Apple.jpg/320px-Red_Apple.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Well-drained loam", difficulty: "Moderate" },
    climate: "Temperate",
    price: "PKR 300–800",
    availability: "Seasonal",
    health: "Rich in fiber, vitamin C. Reduces risk of heart disease.",
    diseases: ["Apple Scab", "Fire Blight", "Powdery Mildew"],
    tags: ["fruit", "temperate", "orchard"],
  },
  {
    name: "Guava",
    scientificName: "Psidium guajava",
    family: "Myrtaceae",
    category: "Trees",
    description: "Tropical fruit tree with fragrant white flowers and vitamin-rich fruits. Very hardy and productive.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Guava_ID.jpg/320px-Guava_ID.jpg",
    careGuide: { water: "Low–Moderate", sunlight: "Full Sun", soil: "Any well-drained", difficulty: "Easy" },
    climate: "Tropical & Subtropical",
    price: "PKR 100–400",
    availability: "Common",
    health: "Highest vitamin C of any fruit. Antibacterial, antioxidant.",
    diseases: ["Anthracnose", "Fruit Fly", "Wilt"],
    tags: ["fruit", "tropical", "medicinal"],
  },
  {
    name: "Papaya",
    scientificName: "Carica papaya",
    family: "Caricaceae",
    category: "Trees",
    description: "Fast-growing tropical tree bearing large orange fruits rich in digestive enzymes.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Papaya_cross_section_BNC.jpg/320px-Papaya_cross_section_BNC.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Sandy loam", difficulty: "Easy" },
    climate: "Tropical",
    price: "PKR 80–250",
    availability: "Year-round",
    health: "Contains papain enzyme. Aids digestion, anti-inflammatory.",
    diseases: ["Papaya Ringspot Virus", "Powdery Mildew", "Root Rot"],
    tags: ["fruit", "tropical", "medicinal"],
  },
  {
    name: "Lemon",
    scientificName: "Citrus limon",
    family: "Rutaceae",
    category: "Trees",
    description: "Evergreen citrus tree producing tart yellow fruits packed with vitamin C.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Lemon_fruit.jpg/320px-Lemon_fruit.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Well-drained sandy loam", difficulty: "Easy" },
    climate: "Subtropical",
    price: "PKR 200–600",
    availability: "Year-round",
    health: "High vitamin C. Antibacterial, aids digestion, kidney stone prevention.",
    diseases: ["Citrus Canker", "Greasy Spot", "Aphids"],
    tags: ["fruit", "citrus", "container-friendly"],
  },
  {
    name: "Pomegranate",
    scientificName: "Punica granatum",
    family: "Lythraceae",
    category: "Shrubs",
    description: "Drought-tolerant shrub producing ruby-red fruits rich in antioxidants.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Pomegranate_fruit_-_single.jpg/320px-Pomegranate_fruit_-_single.jpg",
    careGuide: { water: "Low", sunlight: "Full Sun", soil: "Any well-drained", difficulty: "Easy" },
    climate: "Arid & Mediterranean",
    price: "PKR 300–900",
    availability: "Seasonal",
    health: "Powerful antioxidants. Reduces inflammation, heart disease risk.",
    diseases: ["Fruit Rot", "Leaf Spot", "Aphids"],
    tags: ["fruit", "drought-tolerant", "ornamental"],
  },
  {
    name: "Strawberry",
    scientificName: "Fragaria × ananassa",
    family: "Rosaceae",
    category: "Flowers",
    description: "Low-growing plant producing sweet red berries. Popular in home gardens and containers.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/PerfectStrawberry.jpg/320px-PerfectStrawberry.jpg",
    careGuide: { water: "Regular", sunlight: "Full Sun", soil: "Rich, well-drained", difficulty: "Easy" },
    climate: "Temperate",
    price: "PKR 400–1200",
    availability: "Seasonal",
    health: "High in vitamin C, manganese, folate. Anti-inflammatory.",
    diseases: ["Gray Mold", "Powdery Mildew", "Spider Mites"],
    tags: ["fruit", "container", "berry"],
  },
  {
    name: "Watermelon",
    scientificName: "Citrullus lanatus",
    family: "Cucurbitaceae",
    category: "Vegetables",
    description: "Vine crop producing large, juicy fruits — perfect for hot climates.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Watermelon_seedless.jpg/320px-Watermelon_seedless.jpg",
    careGuide: { water: "Moderate–High", sunlight: "Full Sun", soil: "Sandy loam", difficulty: "Moderate" },
    climate: "Tropical & Subtropical",
    price: "PKR 50–200",
    availability: "Seasonal",
    health: "92% water, lycopene, vitamin A. Hydrating and anti-oxidant rich.",
    diseases: ["Fusarium Wilt", "Anthracnose", "Downy Mildew"],
    tags: ["fruit", "vine", "summer"],
  },
  {
    name: "Grapes",
    scientificName: "Vitis vinifera",
    family: "Vitaceae",
    category: "Shrubs",
    description: "Climbing vine producing clusters of sweet or tart fruits. Used for eating, juice and raisins.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Table_grapes_on_white.jpg/320px-Table_grapes_on_white.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Well-drained loam", difficulty: "Moderate" },
    climate: "Mediterranean & Temperate",
    price: "PKR 300–1000",
    availability: "Seasonal",
    health: "Resveratrol antioxidant. Heart health, anti-aging properties.",
    diseases: ["Powdery Mildew", "Downy Mildew", "Botrytis"],
    tags: ["fruit", "vine", "ornamental"],
  },

  // ───── VEGETABLES ─────
  {
    name: "Tomato",
    scientificName: "Solanum lycopersicum",
    family: "Solanaceae",
    category: "Vegetables",
    description: "Most popular home garden vegetable. Produces red fruits rich in lycopene and vitamins.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/320px-Tomato_je.jpg",
    careGuide: { water: "Regular", sunlight: "Full Sun", soil: "Rich, well-drained", difficulty: "Easy" },
    climate: "Temperate to Tropical",
    price: "PKR 50–200",
    availability: "Year-round",
    health: "High lycopene, vitamin C, K. Reduces cancer risk.",
    diseases: ["Early Blight", "Late Blight", "Blossom End Rot"],
    tags: ["vegetable", "container", "kitchen-garden"],
  },
  {
    name: "Spinach",
    scientificName: "Spinacia oleracea",
    family: "Amaranthaceae",
    category: "Vegetables",
    description: "Fast-growing leafy green packed with iron and nutrients. Ideal for cool seasons.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/2660_Spinacia_oleracea.jpg/320px-2660_Spinacia_oleracea.jpg",
    careGuide: { water: "Regular", sunlight: "Partial to Full Sun", soil: "Rich, moist", difficulty: "Very Easy" },
    climate: "Cool Temperate",
    price: "PKR 30–100",
    availability: "Seasonal",
    health: "Rich in iron, folate, vitamin K. Bone health, energy booster.",
    diseases: ["Downy Mildew", "Leaf Spot", "Aphids"],
    tags: ["vegetable", "leafy", "fast-growing", "kitchen-garden"],
  },
  {
    name: "Potato",
    scientificName: "Solanum tuberosum",
    family: "Solanaceae",
    category: "Vegetables",
    description: "Starchy underground tuber. One of the world's most important food crops.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Potato_and_cross_section.jpg/320px-Potato_and_cross_section.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Loose, well-drained", difficulty: "Easy" },
    climate: "Cool Temperate",
    price: "PKR 40–120",
    availability: "Year-round",
    health: "High in potassium, vitamin C, B6. Energy-dense.",
    diseases: ["Late Blight", "Scab", "Blackleg"],
    tags: ["vegetable", "root", "staple-crop"],
  },
  {
    name: "Onion",
    scientificName: "Allium cepa",
    family: "Amaryllidaceae",
    category: "Vegetables",
    description: "Bulb vegetable essential in cooking worldwide. Strong flavor and medicinal properties.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Onion_on_White.JPG/320px-Onion_on_White.JPG",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Well-drained loam", difficulty: "Easy" },
    climate: "Temperate",
    price: "PKR 30–100",
    availability: "Year-round",
    health: "Quercetin antioxidant. Anti-inflammatory, heart health, antibacterial.",
    diseases: ["Purple Blotch", "Botrytis", "Downy Mildew"],
    tags: ["vegetable", "bulb", "kitchen-staple"],
  },
  {
    name: "Garlic",
    scientificName: "Allium sativum",
    family: "Amaryllidaceae",
    category: "Herbs",
    description: "Pungent bulb used globally in cooking and traditional medicine. Powerful natural antibiotic.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Garlic_bulb.jpg/320px-Garlic_bulb.jpg",
    careGuide: { water: "Low–Moderate", sunlight: "Full Sun", soil: "Loose, well-drained", difficulty: "Very Easy" },
    climate: "Temperate",
    price: "PKR 100–300",
    availability: "Year-round",
    health: "Allicin compound. Antifungal, antibacterial, heart health, immunity.",
    diseases: ["White Rot", "Rust", "Downy Mildew"],
    tags: ["vegetable", "herb", "medicinal", "kitchen-staple"],
  },
  {
    name: "Chili Pepper",
    scientificName: "Capsicum annuum",
    family: "Solanaceae",
    category: "Vegetables",
    description: "Hot or mild peppers used in cuisines worldwide. Easy to grow in pots or garden.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Hot_peppers.jpg/320px-Hot_peppers.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Well-drained rich soil", difficulty: "Easy" },
    climate: "Tropical to Temperate",
    price: "PKR 50–200",
    availability: "Year-round",
    health: "Capsaicin boosts metabolism, pain relief, anti-inflammatory.",
    diseases: ["Bacterial Wilt", "Anthracnose", "Aphids"],
    tags: ["vegetable", "container", "spice", "kitchen-garden"],
  },
  {
    name: "Bitter Gourd (Karela)",
    scientificName: "Momordica charantia",
    family: "Cucurbitaceae",
    category: "Vegetables",
    description: "Tropical vine vegetable famous for its bitter taste and powerful medicinal properties.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Bitter_melon.jpg/320px-Bitter_melon.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Rich loam", difficulty: "Easy" },
    climate: "Tropical",
    price: "PKR 60–180",
    availability: "Seasonal",
    health: "Controls blood sugar. Antidiabetic, liver tonic, antiviral.",
    diseases: ["Powdery Mildew", "Downy Mildew", "Fruit Fly"],
    tags: ["vegetable", "medicinal", "vine", "diabetic-friendly"],
  },
  {
    name: "Pumpkin",
    scientificName: "Cucurbita pepo",
    family: "Cucurbitaceae",
    category: "Vegetables",
    description: "Large vine plant producing orange squash. Nutritious and easy to grow in warm seasons.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/FrenchMarketPumpkinsB.jpg/320px-FrenchMarketPumpkinsB.jpg",
    careGuide: { water: "High", sunlight: "Full Sun", soil: "Rich, moist", difficulty: "Easy" },
    climate: "Temperate to Tropical",
    price: "PKR 80–300",
    availability: "Seasonal",
    health: "Beta-carotene rich. Eye health, immune booster, low calorie.",
    diseases: ["Powdery Mildew", "Squash Vine Borer", "Bacterial Wilt"],
    tags: ["vegetable", "vine", "nutrition-rich"],
  },
  {
    name: "Carrot",
    scientificName: "Daucus carota",
    family: "Apiaceae",
    category: "Vegetables",
    description: "Root vegetable with sweet orange taproots rich in beta-carotene. Ideal for cool seasons.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/320px-Vegetable-Carrot-Bundle-wStalks.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Loose, deep sandy loam", difficulty: "Easy" },
    climate: "Cool Temperate",
    price: "PKR 40–120",
    availability: "Seasonal",
    health: "High beta-carotene, vitamin A. Eye health, antioxidant.",
    diseases: ["Alternaria Blight", "Carrot Fly", "Root Knot Nematode"],
    tags: ["vegetable", "root", "kitchen-garden"],
  },
  {
    name: "Eggplant (Brinjal)",
    scientificName: "Solanum melongena",
    family: "Solanaceae",
    category: "Vegetables",
    description: "Tropical vegetable with glossy purple fruits. Staple in South Asian and Mediterranean cuisine.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Solanum_melongena_24_08_2012.jpg/320px-Solanum_melongena_24_08_2012.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Rich, well-drained", difficulty: "Easy" },
    climate: "Tropical to Subtropical",
    price: "PKR 40–150",
    availability: "Year-round",
    health: "High fiber, antioxidants. Heart health, blood sugar control.",
    diseases: ["Phomopsis Blight", "Bacterial Wilt", "Aphids"],
    tags: ["vegetable", "container", "kitchen-staple"],
  },

  // ───── HERBS ─────
  {
    name: "Tulsi (Holy Basil)",
    scientificName: "Ocimum tenuiflorum",
    family: "Lamiaceae",
    category: "Herbs",
    description: "Sacred herb with exceptional medicinal value. Used in Ayurvedic medicine for centuries.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Tulsi_in_pot.jpg/320px-Tulsi_in_pot.jpg",
    careGuide: { water: "Regular", sunlight: "Full Sun", soil: "Rich moist loam", difficulty: "Easy" },
    climate: "Tropical & Subtropical",
    price: "PKR 80–200",
    availability: "Widely Available",
    health: "Antibacterial, stress relief, respiratory benefits, immunity booster.",
    diseases: ["Fusarium Wilt", "Leaf Blight", "Aphids"],
    tags: ["herb", "medicinal", "indoor", "sacred"],
  },
  {
    name: "Mint",
    scientificName: "Mentha spicata",
    family: "Lamiaceae",
    category: "Herbs",
    description: "Aromatic herb that spreads rapidly. Used in teas, cooking, and traditional medicine.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Spearmint_2.jpg/320px-Spearmint_2.jpg",
    careGuide: { water: "Regular", sunlight: "Partial Sun", soil: "Moist, rich", difficulty: "Very Easy" },
    climate: "Temperate",
    price: "PKR 50–150",
    availability: "Common",
    health: "Relieves indigestion, nausea, headaches. Antibacterial, cooling.",
    diseases: ["Rust", "Powdery Mildew", "Verticillium Wilt"],
    tags: ["herb", "indoor", "container", "medicinal", "culinary"],
  },
  {
    name: "Coriander (Dhaniya)",
    scientificName: "Coriandrum sativum",
    family: "Apiaceae",
    category: "Herbs",
    description: "Fast-growing herb used in cooking across Asia and the Middle East. Both leaves and seeds are used.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Coriander_plants.jpg/320px-Coriander_plants.jpg",
    careGuide: { water: "Regular", sunlight: "Full to Partial Sun", soil: "Well-drained loam", difficulty: "Very Easy" },
    climate: "Cool Temperate",
    price: "PKR 20–80",
    availability: "Widely Available",
    health: "Anti-inflammatory, lowers blood sugar and cholesterol.",
    diseases: ["Powdery Mildew", "Leaf Spot", "Aphids"],
    tags: ["herb", "culinary", "fast-growing", "container"],
  },
  {
    name: "Aloe Vera",
    scientificName: "Aloe barbadensis miller",
    family: "Asphodelaceae",
    category: "Succulents",
    description: "Succulent plant famous for its gel used in skincare and burn treatment. Extremely low maintenance.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Aloe_vera_flower_inset.png/320px-Aloe_vera_flower_inset.png",
    careGuide: { water: "Low", sunlight: "Indirect to Full Sun", soil: "Sandy, well-drained", difficulty: "Very Easy" },
    climate: "Arid & Semi-Arid",
    price: "PKR 100–300",
    availability: "Widely Available",
    health: "Skin healing, digestive aid, anti-inflammatory, burn treatment.",
    diseases: ["Root Rot", "Mealybugs", "Soft Rot"],
    tags: ["medicinal", "indoor", "low-water", "succulent"],
  },
  {
    name: "Fenugreek (Methi)",
    scientificName: "Trigonella foenum-graecum",
    family: "Fabaceae",
    category: "Herbs",
    description: "Multi-purpose herb used in South Asian cuisine. Both leaves and seeds are highly nutritious.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Fenugreek_Leaves_%28Methi%29.jpg/320px-Fenugreek_Leaves_%28Methi%29.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Well-drained loam", difficulty: "Very Easy" },
    climate: "Cool Temperate",
    price: "PKR 30–80",
    availability: "Widely Available",
    health: "Controls blood sugar, boosts testosterone, anti-inflammatory.",
    diseases: ["Powdery Mildew", "Root Rot", "Charcoal Rot"],
    tags: ["herb", "culinary", "medicinal", "fast-growing"],
  },
  {
    name: "Ginger",
    scientificName: "Zingiber officinale",
    family: "Zingiberaceae",
    category: "Herbs",
    description: "Tropical rhizome used as spice and medicine. One of the most widely used medicinal plants.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Ginger_roots.jpg/320px-Ginger_roots.jpg",
    careGuide: { water: "Regular", sunlight: "Partial Shade", soil: "Rich, moist", difficulty: "Moderate" },
    climate: "Tropical",
    price: "PKR 100–350",
    availability: "Year-round",
    health: "Anti-nausea, anti-inflammatory, aids digestion, immune support.",
    diseases: ["Soft Rot", "Bacterial Wilt", "Rhizome Rot"],
    tags: ["herb", "spice", "medicinal", "container"],
  },
  {
    name: "Turmeric",
    scientificName: "Curcuma longa",
    family: "Zingiberaceae",
    category: "Herbs",
    description: "Tropical rhizome producing golden spice. One of nature's most powerful anti-inflammatory agents.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Curcuma_longa_roots.jpg/320px-Curcuma_longa_roots.jpg",
    careGuide: { water: "Regular", sunlight: "Partial to Full Sun", soil: "Rich, well-drained", difficulty: "Easy" },
    climate: "Tropical",
    price: "PKR 150–400",
    availability: "Common",
    health: "Curcumin compound. Powerful anti-inflammatory, antioxidant, brain health.",
    diseases: ["Rhizome Rot", "Leaf Blotch", "Leaf Spot"],
    tags: ["herb", "spice", "medicinal", "ayurvedic"],
  },
  {
    name: "Curry Leaf",
    scientificName: "Murraya koenigii",
    family: "Rutaceae",
    category: "Trees",
    description: "Aromatic shrub/tree native to South Asia. Leaves are essential in Indian and Pakistani cooking.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Curry_leaf_plant.jpg/320px-Curry_leaf_plant.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Well-drained sandy loam", difficulty: "Easy" },
    climate: "Tropical & Subtropical",
    price: "PKR 100–400",
    availability: "Common",
    health: "Antidiabetic, antioxidant, reduces cholesterol.",
    diseases: ["Leaf Spot", "Scale Insects", "Psyllids"],
    tags: ["herb", "culinary", "container", "aromatic"],
  },

  // ───── INDOOR PLANTS ─────
  {
    name: "Money Plant",
    scientificName: "Epipremnum aureum",
    family: "Araceae",
    category: "Shrubs",
    description: "Popular indoor vine known for air purification and easy propagation. Thrives in low light.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Epipremnum_aureum_31082012.jpg/320px-Epipremnum_aureum_31082012.jpg",
    careGuide: { water: "Low–Moderate", sunlight: "Low to Indirect", soil: "Any potting mix", difficulty: "Very Easy" },
    climate: "Tropical",
    price: "PKR 100–500",
    availability: "Very Common",
    health: "Removes formaldehyde, benzene from air. Reduces stress.",
    diseases: ["Root Rot", "Bacterial Wilt", "Mealybugs"],
    tags: ["indoor", "air-purifier", "low-light", "vine"],
  },
  {
    name: "Peace Lily",
    scientificName: "Spathiphyllum wallisii",
    family: "Araceae",
    category: "Flowers",
    description: "Elegant indoor plant with white flowers. One of NASA's top air-purifying plants.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Spathiphyllum_cochlearispathum_RTBG.jpg/320px-Spathiphyllum_cochlearispathum_RTBG.jpg",
    careGuide: { water: "Moderate", sunlight: "Low to Indirect", soil: "Peat-based potting mix", difficulty: "Easy" },
    climate: "Tropical",
    price: "PKR 300–800",
    availability: "Common",
    health: "Removes benzene, formaldehyde, ammonia from air.",
    diseases: ["Root Rot", "Leaf Blight", "Mealybugs"],
    tags: ["indoor", "air-purifier", "flowering", "low-light"],
  },
  {
    name: "Snake Plant",
    scientificName: "Sansevieria trifasciata",
    family: "Asparagaceae",
    category: "Succulents",
    description: "Nearly indestructible indoor plant that purifies air even at night. Perfect for beginners.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg/320px-Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg",
    careGuide: { water: "Very Low", sunlight: "Any light", soil: "Well-drained sandy", difficulty: "Very Easy" },
    climate: "Tropical & Arid",
    price: "PKR 150–500",
    availability: "Very Common",
    health: "Produces oxygen at night. Removes toxins from air.",
    diseases: ["Root Rot", "Southern Blight", "Red Leaf Spot"],
    tags: ["indoor", "air-purifier", "low-maintenance", "beginner"],
  },
  {
    name: "Rubber Plant",
    scientificName: "Ficus elastica",
    family: "Moraceae",
    category: "Trees",
    description: "Bold indoor tree with large glossy leaves. Excellent air purifier and statement plant.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Ficus_elastica.jpg/320px-Ficus_elastica.jpg",
    careGuide: { water: "Moderate", sunlight: "Bright Indirect", soil: "Well-drained potting mix", difficulty: "Easy" },
    climate: "Tropical",
    price: "PKR 400–1500",
    availability: "Common",
    health: "Purifies indoor air, absorbs carbon dioxide.",
    diseases: ["Root Rot", "Leaf Drop", "Mealybugs"],
    tags: ["indoor", "air-purifier", "statement-plant"],
  },
  {
    name: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    family: "Asparagaceae",
    category: "Flowers",
    description: "Hardy hanging plant with arching green and white striped leaves. Easy to propagate.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Spider_Plant.jpg/320px-Spider_Plant.jpg",
    careGuide: { water: "Moderate", sunlight: "Indirect", soil: "Any well-drained", difficulty: "Very Easy" },
    climate: "Temperate to Tropical",
    price: "PKR 150–400",
    availability: "Very Common",
    health: "Removes CO, formaldehyde. Safe for pets.",
    diseases: ["Root Rot", "Tip Burn", "Scale"],
    tags: ["indoor", "hanging", "pet-safe", "beginner"],
  },
  {
    name: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    family: "Araceae",
    category: "Shrubs",
    description: "Extremely drought-tolerant indoor plant with glossy dark green leaves. Nearly impossible to kill.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/ZZ_Plant_%28Zamioculcas_zamiifolia%29.jpg/320px-ZZ_Plant_%28Zamioculcas_zamiifolia%29.jpg",
    careGuide: { water: "Very Low", sunlight: "Low to Bright Indirect", soil: "Well-drained potting mix", difficulty: "Very Easy" },
    climate: "Tropical",
    price: "PKR 300–900",
    availability: "Common",
    health: "Air purifier. Tolerates neglect.",
    diseases: ["Root Rot", "Stem Rot"],
    tags: ["indoor", "low-maintenance", "low-light", "drought-tolerant"],
  },
  {
    name: "Jade Plant",
    scientificName: "Crassula ovata",
    family: "Crassulaceae",
    category: "Succulents",
    description: "Succulent with thick oval leaves. Long-lived indoor plant considered lucky in many cultures.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Crassula_ovata.jpg/320px-Crassula_ovata.jpg",
    careGuide: { water: "Low", sunlight: "Bright Indirect to Full Sun", soil: "Succulent mix", difficulty: "Very Easy" },
    climate: "Arid",
    price: "PKR 200–600",
    availability: "Common",
    health: "Air purifier. Symbolic of good luck and prosperity.",
    diseases: ["Root Rot", "Powdery Mildew", "Mealybugs"],
    tags: ["indoor", "succulent", "lucky-plant", "low-water"],
  },
  {
    name: "Bamboo Palm",
    scientificName: "Dypsis lutescens",
    family: "Arecaceae",
    category: "Trees",
    description: "Elegant indoor palm with feathery fronds. Excellent air purifier and humidity regulator.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Dypsis_lutescens1.jpg/320px-Dypsis_lutescens1.jpg",
    careGuide: { water: "Moderate", sunlight: "Indirect to Bright", soil: "Well-drained potting mix", difficulty: "Easy" },
    climate: "Tropical",
    price: "PKR 500–2000",
    availability: "Common",
    health: "Removes benzene, trichloroethylene. Adds humidity.",
    diseases: ["Root Rot", "Spider Mites", "Scale"],
    tags: ["indoor", "air-purifier", "tropical", "statement-plant"],
  },

  // ───── FLOWERS ─────
  {
    name: "Rose",
    scientificName: "Rosa hybrid",
    family: "Rosaceae",
    category: "Flowers",
    description: "Classic flowering shrub prized for its beautiful blooms and fragrance. Available in hundreds of cultivars.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Rosa_'Ingrid_Bergman'.jpg/320px-Rosa_'Ingrid_Bergman'.jpg",
    careGuide: { water: "Regular", sunlight: "Full Sun", soil: "Rich, moist well-drained", difficulty: "Moderate" },
    climate: "Temperate",
    price: "PKR 200–1200",
    availability: "Common",
    health: "Aromatherapy benefits. Vitamin C in rose hips. Stress relief.",
    diseases: ["Black Spot", "Aphids", "Rust", "Powdery Mildew"],
    tags: ["flower", "ornamental", "fragrant", "garden"],
  },
  {
    name: "Marigold",
    scientificName: "Tagetes erecta",
    family: "Asteraceae",
    category: "Flowers",
    description: "Vibrant orange and yellow flowers. Natural pest repellent and used in religious ceremonies across South Asia.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Marigold_flowers.jpg/320px-Marigold_flowers.jpg",
    careGuide: { water: "Low–Moderate", sunlight: "Full Sun", soil: "Any well-drained", difficulty: "Very Easy" },
    climate: "Tropical to Temperate",
    price: "PKR 50–200",
    availability: "Widely Available",
    health: "Antiseptic, anti-inflammatory. Used in wound healing.",
    diseases: ["Powdery Mildew", "Botrytis", "Root Rot"],
    tags: ["flower", "pest-repellent", "ornamental", "religious"],
  },
  {
    name: "Sunflower",
    scientificName: "Helianthus annuus",
    family: "Asteraceae",
    category: "Flowers",
    description: "Tall annual flower with large golden heads that track the sun. Seeds are edible and oil-rich.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Sunflower_sky_backdrop.jpg/320px-Sunflower_sky_backdrop.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Well-drained loam", difficulty: "Very Easy" },
    climate: "Temperate",
    price: "PKR 50–150",
    availability: "Seasonal",
    health: "Seeds rich in vitamin E, selenium. Heart health.",
    diseases: ["Downy Mildew", "Rust", "Sclerotinia"],
    tags: ["flower", "edible-seeds", "ornamental", "annual"],
  },
  {
    name: "Jasmine",
    scientificName: "Jasminum officinale",
    family: "Oleaceae",
    category: "Shrubs",
    description: "Climbing shrub with intensely fragrant white flowers. Used in perfumery and herbal teas.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/White_jasmine_flowers.jpg/320px-White_jasmine_flowers.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun to Partial Shade", soil: "Well-drained loam", difficulty: "Easy" },
    climate: "Tropical to Temperate",
    price: "PKR 150–500",
    availability: "Common",
    health: "Reduces anxiety, improves sleep. Antioxidant properties.",
    diseases: ["Root Rot", "Blight", "Scale Insects"],
    tags: ["flower", "fragrant", "ornamental", "tea"],
  },
  {
    name: "Hibiscus",
    scientificName: "Hibiscus rosa-sinensis",
    family: "Malvaceae",
    category: "Shrubs",
    description: "Tropical shrub with large, showy flowers. Used in herbal teas and traditional medicine.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Single_flower_of_Hibiscus_rosa-sinensis.jpg/320px-Single_flower_of_Hibiscus_rosa-sinensis.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Rich, well-drained", difficulty: "Easy" },
    climate: "Tropical & Subtropical",
    price: "PKR 200–700",
    availability: "Common",
    health: "Lowers blood pressure, rich in vitamin C, antioxidants.",
    diseases: ["Leaf Spot", "Root Rot", "Aphids", "Whitefly"],
    tags: ["flower", "ornamental", "medicinal", "tea"],
  },
  {
    name: "Dahlia",
    scientificName: "Dahlia pinnata",
    family: "Asteraceae",
    category: "Flowers",
    description: "Spectacular flowering plant with blooms in every color except blue. Tuber-based perennial.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Single_Dahlia.jpg/320px-Single_Dahlia.jpg",
    careGuide: { water: "Regular", sunlight: "Full Sun", soil: "Rich, well-drained", difficulty: "Moderate" },
    climate: "Temperate",
    price: "PKR 300–1000",
    availability: "Seasonal",
    health: "Ornamental. Edible tubers in some varieties.",
    diseases: ["Powdery Mildew", "Botrytis", "Dahlia Mosaic Virus"],
    tags: ["flower", "ornamental", "garden", "colorful"],
  },
  {
    name: "Bougainvillea",
    scientificName: "Bougainvillea spectabilis",
    family: "Nyctaginaceae",
    category: "Shrubs",
    description: "Vigorous climbing shrub with stunning papery bracts in pink, purple, red, or orange.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Bougainvillea_spectabilis3.jpg/320px-Bougainvillea_spectabilis3.jpg",
    careGuide: { water: "Low", sunlight: "Full Sun", soil: "Well-drained", difficulty: "Easy" },
    climate: "Tropical & Subtropical",
    price: "PKR 200–800",
    availability: "Common",
    health: "Traditional use for cough, skin conditions.",
    diseases: ["Root Rot", "Leaf Spot", "Scale"],
    tags: ["flower", "ornamental", "drought-tolerant", "climber"],
  },
  {
    name: "Lavender",
    scientificName: "Lavandula angustifolia",
    family: "Lamiaceae",
    category: "Herbs",
    description: "Fragrant purple flowering herb used in aromatherapy, perfumery, and culinary applications.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Bee_on_lavender_at_New_Lanark.jpg/320px-Bee_on_lavender_at_New_Lanark.jpg",
    careGuide: { water: "Low", sunlight: "Full Sun", soil: "Sandy, well-drained", difficulty: "Easy" },
    climate: "Mediterranean",
    price: "PKR 300–900",
    availability: "Moderate",
    health: "Reduces anxiety, insomnia. Antifungal, antibacterial.",
    diseases: ["Root Rot", "Shab", "Septoria Leaf Spot"],
    tags: ["flower", "herb", "fragrant", "medicinal", "aromatherapy"],
  },

  // ───── TREES ─────
  {
    name: "Neem Tree",
    scientificName: "Azadirachta indica",
    family: "Meliaceae",
    category: "Trees",
    description: "Fast-growing tree known for its medicinal properties. Used as natural pesticide and in traditional medicine.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Azadirachta_indica_%28Neem%29_in_Hyderabad%2C_AP_W_IMG_0511.jpg/320px-Azadirachta_indica_%28Neem%29_in_Hyderabad%2C_AP_W_IMG_0511.jpg",
    careGuide: { water: "Low", sunlight: "Full Sun", soil: "Well-drained loamy", difficulty: "Easy" },
    climate: "Tropical & Subtropical",
    price: "PKR 150–400",
    availability: "Widely Available",
    health: "Antibacterial, antifungal. Purifies air. Dental health.",
    diseases: ["Powdery Mildew", "Leaf Spot", "Sooty Mold"],
    tags: ["medicinal", "shade", "fast-growing", "plantation"],
  },
  {
    name: "Eucalyptus",
    scientificName: "Eucalyptus globulus",
    family: "Myrtaceae",
    category: "Trees",
    description: "Fast-growing plantation tree with aromatic leaves. Used for timber, essential oils, and paper.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Starr_031108-0007_Eucalyptus_globulus.jpg/320px-Starr_031108-0007_Eucalyptus_globulus.jpg",
    careGuide: { water: "Low–Moderate", sunlight: "Full Sun", soil: "Well-drained", difficulty: "Easy" },
    climate: "Mediterranean to Tropical",
    price: "PKR 100–300",
    availability: "Common",
    health: "Decongestant, antibacterial, anti-inflammatory oil.",
    diseases: ["Leaf Scorch", "Canker", "Psyllids"],
    tags: ["plantation", "timber", "medicinal", "fast-growing"],
  },
  {
    name: "Banyan Tree",
    scientificName: "Ficus benghalensis",
    family: "Moraceae",
    category: "Trees",
    description: "Sacred tree of India with aerial roots that form additional trunks. Can cover massive areas.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Banyan_tree_from_Thiruvananathapuram.jpg/320px-Banyan_tree_from_Thiruvananathapuram.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Any well-drained", difficulty: "Easy" },
    climate: "Tropical",
    price: "PKR 200–600",
    availability: "Common",
    health: "Bark used in diabetes treatment. Antioxidant.",
    diseases: ["Leaf Spot", "Blight", "Scale"],
    tags: ["shade", "sacred", "ornamental", "plantation"],
  },
  {
    name: "Coconut Palm",
    scientificName: "Cocos nucifera",
    family: "Arecaceae",
    category: "Trees",
    description: "The tree of life. Every part is useful — fruit, oil, shell, fiber, and timber.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Coconut_on_the_coconut_tree.jpg/320px-Coconut_on_the_coconut_tree.jpg",
    careGuide: { water: "Moderate–High", sunlight: "Full Sun", soil: "Sandy, well-drained", difficulty: "Moderate" },
    climate: "Tropical Coastal",
    price: "PKR 500–2000",
    availability: "Common",
    health: "Electrolytes in water, MCTs in oil. Antiviral, antimicrobial.",
    diseases: ["Bud Rot", "Coconut Mite", "Root Wilt"],
    tags: ["fruit", "plantation", "coastal", "multi-purpose"],
  },
  {
    name: "Date Palm",
    scientificName: "Phoenix dactylifera",
    family: "Arecaceae",
    category: "Trees",
    description: "Ancient desert tree producing nutrient-rich dates. Culturally significant in the Middle East and South Asia.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Phoenix_dactylifera_3.jpg/320px-Phoenix_dactylifera_3.jpg",
    careGuide: { water: "Low", sunlight: "Full Sun", soil: "Sandy, well-drained", difficulty: "Moderate" },
    climate: "Arid & Desert",
    price: "PKR 1000–5000",
    availability: "Moderate",
    health: "High in fiber, potassium, magnesium. Natural energy booster.",
    diseases: ["Bayoud Disease", "Black Scorch", "Bud Rot"],
    tags: ["fruit", "desert", "sacred", "plantation"],
  },
  {
    name: "Mulberry",
    scientificName: "Morus alba",
    family: "Moraceae",
    category: "Trees",
    description: "Fast-growing tree producing sweet berries. Also used for silkworm cultivation.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/White_mulberry_fruit_in_Ghorveh.jpg/320px-White_mulberry_fruit_in_Ghorveh.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Well-drained loam", difficulty: "Easy" },
    climate: "Temperate to Subtropical",
    price: "PKR 200–600",
    availability: "Common",
    health: "Antioxidant anthocyanins. Blood sugar control.",
    diseases: ["Leaf Spot", "Canker", "Root Rot"],
    tags: ["fruit", "shade", "fast-growing", "plantation"],
  },
  {
    name: "Peepal Tree",
    scientificName: "Ficus religiosa",
    family: "Moraceae",
    category: "Trees",
    description: "Sacred fig tree revered in Buddhism and Hinduism. Excellent oxygen producer.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Ficus_religiosa_Bo.jpg/320px-Ficus_religiosa_Bo.jpg",
    careGuide: { water: "Low", sunlight: "Full Sun", soil: "Any", difficulty: "Very Easy" },
    climate: "Tropical",
    price: "PKR 100–400",
    availability: "Common",
    health: "Produces oxygen 24/7. Bark used in traditional medicine.",
    diseases: ["Leaf Spot", "Root Rot"],
    tags: ["sacred", "shade", "plantation", "medicinal"],
  },

  // ───── SUCCULENTS & CACTI ─────
  {
    name: "Cactus (Barrel)",
    scientificName: "Ferocactus cylindraceus",
    family: "Cactaceae",
    category: "Succulents",
    description: "Iconic barrel-shaped desert cactus. Stores water in its body. Near-zero maintenance.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Ferocactus_cylindraceus.jpg/320px-Ferocactus_cylindraceus.jpg",
    careGuide: { water: "Very Low", sunlight: "Full Sun", soil: "Sandy, well-drained", difficulty: "Very Easy" },
    climate: "Desert & Arid",
    price: "PKR 200–800",
    availability: "Common",
    health: "Decorative. Reduces indoor stress.",
    diseases: ["Root Rot", "Scale Insects", "Bacterial Rot"],
    tags: ["indoor", "succulent", "low-water", "desert"],
  },
  {
    name: "Echeveria",
    scientificName: "Echeveria elegans",
    family: "Crassulaceae",
    category: "Succulents",
    description: "Beautiful rosette-forming succulent in stunning colors. Perfect for windowsills and containers.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Echeveria_elegans.jpg/320px-Echeveria_elegans.jpg",
    careGuide: { water: "Low", sunlight: "Bright Indirect to Full Sun", soil: "Succulent mix", difficulty: "Very Easy" },
    climate: "Arid",
    price: "PKR 150–500",
    availability: "Common",
    health: "Air purifier. Aesthetic mental health benefits.",
    diseases: ["Root Rot", "Mealybugs", "Leaf Drop"],
    tags: ["indoor", "succulent", "decorative", "container"],
  },

  // ───── PLANTATION TREES ─────
  {
    name: "Sheesham (Rosewood)",
    scientificName: "Dalbergia sissoo",
    family: "Fabaceae",
    category: "Trees",
    description: "Fast-growing nitrogen-fixing timber tree. National tree of Pakistan. Excellent shade provider.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Dalbergia_sissoo.jpg/320px-Dalbergia_sissoo.jpg",
    careGuide: { water: "Low", sunlight: "Full Sun", soil: "Any well-drained", difficulty: "Easy" },
    climate: "Tropical & Subtropical",
    price: "PKR 150–500",
    availability: "Widely Available",
    health: "Nitrogen fixer. Wood used medicinally in Ayurveda.",
    diseases: ["Die Back", "Root Rot", "Leaf Rust"],
    tags: ["timber", "plantation", "shade", "nitrogen-fixing"],
  },
  {
    name: "Poplar",
    scientificName: "Populus deltoides",
    family: "Salicaceae",
    category: "Trees",
    description: "Extremely fast-growing plantation tree. Used for paper, plywood, and agroforestry in Pakistan.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Populus_nigra_bark.jpg/320px-Populus_nigra_bark.jpg",
    careGuide: { water: "High", sunlight: "Full Sun", soil: "Moist, fertile", difficulty: "Easy" },
    climate: "Temperate",
    price: "PKR 100–400",
    availability: "Widely Available",
    health: "Bark has analgesic properties.",
    diseases: ["Leaf Rust", "Canker", "Leaf Spot"],
    tags: ["timber", "plantation", "fast-growing", "agroforestry"],
  },
  {
    name: "Chikoo (Sapodilla)",
    scientificName: "Manilkara zapota",
    family: "Sapotaceae",
    category: "Trees",
    description: "Tropical fruit tree bearing brown oval fruits with caramel-like sweet flesh.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Sapodilla_Chikoo_Fruit_in_India.jpg/320px-Sapodilla_Chikoo_Fruit_in_India.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Sandy loam", difficulty: "Easy" },
    climate: "Tropical",
    price: "PKR 300–800",
    availability: "Seasonal",
    health: "High tannins, anti-diarrheal. Rich in vitamins A, C.",
    diseases: ["Leaf Spot", "Fruit Fly", "Sooty Mold"],
    tags: ["fruit", "tropical", "shade"],
  },
  {
    name: "Jackfruit",
    scientificName: "Artocarpus heterophyllus",
    family: "Moraceae",
    category: "Trees",
    description: "World's largest tree-borne fruit. Young fruit used as meat substitute; ripe fruit is sweet.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Jackfruit.jpg/320px-Jackfruit.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Deep, well-drained loam", difficulty: "Easy" },
    climate: "Tropical",
    price: "PKR 400–1500",
    availability: "Seasonal",
    health: "High in fiber, vitamins A, C, B6. Antioxidant.",
    diseases: ["Fruit Rot", "Rhizopus Rot", "Bark Borer"],
    tags: ["fruit", "tropical", "shade", "vegan-meat"],
  },
  {
    name: "Lychee",
    scientificName: "Litchi chinensis",
    family: "Sapindaceae",
    category: "Trees",
    description: "Subtropical fruit tree producing sweet, juicy fruits with bumpy red skin.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Lychee_white_BNC.jpg/320px-Lychee_white_BNC.jpg",
    careGuide: { water: "Regular", sunlight: "Full Sun", soil: "Well-drained acidic", difficulty: "Moderate" },
    climate: "Subtropical",
    price: "PKR 500–1800",
    availability: "Seasonal",
    health: "High in vitamin C, potassium. Anti-inflammatory.",
    diseases: ["Anthracnose", "Root Rot", "Erinose Mite"],
    tags: ["fruit", "subtropical", "premium"],
  },
  {
    name: "Peach",
    scientificName: "Prunus persica",
    family: "Rosaceae",
    category: "Trees",
    description: "Deciduous fruit tree producing fragrant, fuzzy-skinned stone fruits.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Autumn_Red_peaches.jpg/320px-Autumn_Red_peaches.jpg",
    careGuide: { water: "Moderate", sunlight: "Full Sun", soil: "Well-drained sandy loam", difficulty: "Moderate" },
    climate: "Temperate",
    price: "PKR 400–1200",
    availability: "Seasonal",
    health: "Rich in antioxidants, vitamins A, C. Good for skin.",
    diseases: ["Leaf Curl", "Brown Rot", "Powdery Mildew"],
    tags: ["fruit", "temperate", "orchard"],
  },
  {
    name: "Apricot",
    scientificName: "Prunus armeniaca",
    family: "Rosaceae",
    category: "Trees",
    description: "Small deciduous tree growing orange stone fruits. Widely cultivated in Gilgit-Baltistan.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Apricot_and_cross_section.jpg/320px-Apricot_and_cross_section.jpg",
    careGuide: { water: "Low–Moderate", sunlight: "Full Sun", soil: "Well-drained loam", difficulty: "Easy" },
    climate: "Cold Temperate",
    price: "PKR 300–1000",
    availability: "Seasonal",
    health: "High in beta-carotene, vitamin A. Eye health.",
    diseases: ["Bacterial Canker", "Brown Rot", "Cytospora Canker"],
    tags: ["fruit", "mountain", "orchard", "pakistan"],
  },
  {
    name: "Fig",
    scientificName: "Ficus carica",
    family: "Moraceae",
    category: "Trees",
    description: "Ancient fruit tree producing sweet, seed-filled fruits. Drought tolerant once established.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Figues_sur_un_figuier.jpg/320px-Figues_sur_un_figuier.jpg",
    careGuide: { water: "Low–Moderate", sunlight: "Full Sun", soil: "Any well-drained", difficulty: "Easy" },
    climate: "Mediterranean to Subtropical",
    price: "PKR 300–900",
    availability: "Seasonal",
    health: "High in fiber, calcium, potassium. Digestive health.",
    diseases: ["Fig Mosaic Virus", "Root Knot", "Canker"],
    tags: ["fruit", "drought-tolerant", "orchard", "sacred"],
  },

  // ───── SHRUBS ─────
  {
    name: "Henna (Mehndi)",
    scientificName: "Lawsonia inermis",
    family: "Lythraceae",
    category: "Shrubs",
    description: "Shrub whose leaves produce natural orange-red dye used in body art and hair coloring.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Lawsonia_inermis1.jpg/320px-Lawsonia_inermis1.jpg",
    careGuide: { water: "Low", sunlight: "Full Sun", soil: "Well-drained sandy", difficulty: "Easy" },
    climate: "Tropical & Arid",
    price: "PKR 100–400",
    availability: "Common",
    health: "Antifungal, antibacterial. Cools body temperature.",
    diseases: ["Leaf Spot", "Root Rot"],
    tags: ["medicinal", "cosmetic", "cultural", "drought-tolerant"],
  },
  {
    name: "Oleander",
    scientificName: "Nerium oleander",
    family: "Apocynaceae",
    category: "Shrubs",
    description: "Ornamental shrub with showy pink or white flowers. Extremely drought tolerant.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Nerium_oleander_flowers_leaves.jpg/320px-Nerium_oleander_flowers_leaves.jpg",
    careGuide: { water: "Low", sunlight: "Full Sun", soil: "Any well-drained", difficulty: "Very Easy" },
    climate: "Mediterranean & Subtropical",
    price: "PKR 100–400",
    availability: "Common",
    health: "Ornamental. Note: Toxic if ingested.",
    diseases: ["Leaf Scorch", "Bacterial Gall", "Scale"],
    tags: ["ornamental", "drought-tolerant", "roadside", "toxic"],
  },
  {
    name: "Croton",
    scientificName: "Codiaeum variegatum",
    family: "Euphorbiaceae",
    category: "Shrubs",
    description: "Vibrant tropical shrub with multicolored leaves in red, yellow, orange, and green.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Croton_Codiaeum_variegatum.jpg/320px-Croton_Codiaeum_variegatum.jpg",
    careGuide: { water: "Moderate", sunlight: "Bright Indirect to Full Sun", soil: "Well-drained rich", difficulty: "Moderate" },
    climate: "Tropical",
    price: "PKR 200–600",
    availability: "Common",
    health: "Air purifier. Traditional medicinal uses.",
    diseases: ["Root Rot", "Mealybugs", "Spider Mites"],
    tags: ["indoor", "ornamental", "colorful", "tropical"],
  },

  // ───── MORE INDOOR / COMMON ─────
  {
    name: "Pothos (Devil's Ivy)",
    scientificName: "Epipremnum pinnatum",
    family: "Araceae",
    category: "Shrubs",
    description: "Trailing vine with heart-shaped leaves. Virtually indestructible and thrives in any condition.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Epipremnum_pinnatum_Indonesia.jpg/320px-Epipremnum_pinnatum_Indonesia.jpg",
    careGuide: { water: "Low", sunlight: "Any", soil: "Any potting mix", difficulty: "Very Easy" },
    climate: "Tropical",
    price: "PKR 100–400",
    availability: "Very Common",
    health: "Air purifier. Removes xylene, benzene.",
    diseases: ["Root Rot", "Bacterial Wilt"],
    tags: ["indoor", "low-light", "hanging", "beginner"],
  },
  {
    name: "Philodendron",
    scientificName: "Philodendron hederaceum",
    family: "Araceae",
    category: "Shrubs",
    description: "Classic trailing or climbing indoor plant with heart-shaped glossy leaves.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Philodendron_hederaceum.jpg/320px-Philodendron_hederaceum.jpg",
    careGuide: { water: "Moderate", sunlight: "Indirect", soil: "Well-drained potting mix", difficulty: "Very Easy" },
    climate: "Tropical",
    price: "PKR 200–700",
    availability: "Common",
    health: "Air purifier. Removes formaldehyde.",
    diseases: ["Root Rot", "Bacterial Blight", "Mealybugs"],
    tags: ["indoor", "tropical", "low-light", "hanging"],
  },
  {
    name: "Dracaena",
    scientificName: "Dracaena marginata",
    family: "Asparagaceae",
    category: "Trees",
    description: "Striking indoor tree with long thin leaves edged in red. Excellent air purifier.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Dracaena_marginata.jpg/320px-Dracaena_marginata.jpg",
    careGuide: { water: "Low", sunlight: "Indirect", soil: "Well-drained potting mix", difficulty: "Very Easy" },
    climate: "Tropical",
    price: "PKR 400–1500",
    availability: "Common",
    health: "Removes benzene, formaldehyde, trichloroethylene.",
    diseases: ["Root Rot", "Fluoride Toxicity", "Scale"],
    tags: ["indoor", "air-purifier", "statement-plant"],
  },
  {
    name: "Chinese Evergreen",
    scientificName: "Aglaonema commutatum",
    family: "Araceae",
    category: "Shrubs",
    description: "Low-maintenance indoor plant with beautiful patterned leaves. Extremely tolerant of neglect.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Aglaonema_commutatum2.jpg/320px-Aglaonema_commutatum2.jpg",
    careGuide: { water: "Low–Moderate", sunlight: "Low to Indirect", soil: "Well-drained potting mix", difficulty: "Very Easy" },
    climate: "Tropical",
    price: "PKR 300–800",
    availability: "Common",
    health: "Air purifier. One of easiest plants to keep alive.",
    diseases: ["Root Rot", "Bacterial Blight", "Mealybugs"],
    tags: ["indoor", "low-light", "beginner", "ornamental"],
  },
  {
    name: "Boston Fern",
    scientificName: "Nephrolepis exaltata",
    family: "Nephrolepidaceae",
    category: "Flowers",
    description: "Lush hanging fern with feathery fronds. Excellent humidity regulator and air purifier.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Boston_fern_2.jpg/320px-Boston_fern_2.jpg",
    careGuide: { water: "Regular", sunlight: "Indirect", soil: "Peat-based moist mix", difficulty: "Moderate" },
    climate: "Tropical",
    price: "PKR 300–900",
    availability: "Common",
    health: "Removes formaldehyde, xylene. Adds humidity.",
    diseases: ["Root Rot", "Scale", "Fusarium Wilt"],
    tags: ["indoor", "hanging", "air-purifier", "humidity"],
  },
  {
    name: "Adenium (Desert Rose)",
    scientificName: "Adenium obesum",
    family: "Apocynaceae",
    category: "Succulents",
    description: "Stunning succulent with a swollen trunk and brilliant pink or red flowers.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Adenium_obesum3.jpg/320px-Adenium_obesum3.jpg",
    careGuide: { water: "Low", sunlight: "Full Sun", soil: "Sandy, well-drained", difficulty: "Easy" },
    climate: "Arid & Tropical",
    price: "PKR 500–2000",
    availability: "Moderate",
    health: "Ornamental. Traditional wound healing uses.",
    diseases: ["Root Rot", "Stem Rot", "Scale"],
    tags: ["indoor", "succulent", "flowering", "ornamental"],
  },
  {
    name: "Chrysanthemum",
    scientificName: "Chrysanthemum morifolium",
    family: "Asteraceae",
    category: "Flowers",
    description: "Beloved flowering plant with dense, colorful blooms. Used in teas and traditional medicine.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image-Chrysanthemum_sp.jpg/320px-Image-Chrysanthemum_sp.jpg",
    careGuide: { water: "Regular", sunlight: "Full Sun", soil: "Rich, well-drained", difficulty: "Moderate" },
    climate: "Temperate",
    price: "PKR 200–600",
    availability: "Seasonal",
    health: "Anti-inflammatory, antioxidant tea. Reduces fever.",
    diseases: ["Powdery Mildew", "Leaf Spot", "Aphids"],
    tags: ["flower", "ornamental", "medicinal", "tea"],
  },
  {
    name: "Portulaca (Moss Rose)",
    scientificName: "Portulaca grandiflora",
    family: "Portulacaceae",
    category: "Flowers",
    description: "Vibrant low-growing succulent flower perfect for hot, dry conditions. Blooms all summer.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Portulaca_grandiflora.jpg/320px-Portulaca_grandiflora.jpg",
    careGuide: { water: "Very Low", sunlight: "Full Sun", soil: "Sandy, poor soil", difficulty: "Very Easy" },
    climate: "Tropical to Temperate",
    price: "PKR 50–200",
    availability: "Common",
    health: "Ornamental. Edible in some cultures.",
    diseases: ["Root Rot", "Aphids"],
    tags: ["flower", "drought-tolerant", "container", "colorful"],
  },
  {
    name: "Impatiens",
    scientificName: "Impatiens walleriana",
    family: "Balsaminaceae",
    category: "Flowers",
    description: "Prolific flowering annual perfect for shaded gardens. Blooms in vivid colors continuously.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Impatiens_walleriana_flowers.jpg/320px-Impatiens_walleriana_flowers.jpg",
    careGuide: { water: "Regular", sunlight: "Shade to Partial Sun", soil: "Rich, moist", difficulty: "Easy" },
    climate: "Tropical",
    price: "PKR 100–300",
    availability: "Common",
    health: "Ornamental.",
    diseases: ["Downy Mildew", "Botrytis", "Root Rot"],
    tags: ["flower", "shade", "container", "colorful"],
  },
  {
    name: "Anthurium",
    scientificName: "Anthurium andraeanum",
    family: "Araceae",
    category: "Flowers",
    description: "Exotic indoor plant with waxy heart-shaped spathes in red, pink, or white. Long-lasting blooms.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Anthurium_andraeanum.jpg/320px-Anthurium_andraeanum.jpg",
    careGuide: { water: "Moderate", sunlight: "Indirect", soil: "Well-drained orchid mix", difficulty: "Moderate" },
    climate: "Tropical",
    price: "PKR 500–2000",
    availability: "Moderate",
    health: "Air purifier. Removes ammonia, formaldehyde.",
    diseases: ["Root Rot", "Bacterial Blight", "Mealybugs"],
    tags: ["indoor", "flowering", "ornamental", "air-purifier"],
  },
  {
    name: "Kalanchoe",
    scientificName: "Kalanchoe blossfeldiana",
    family: "Crassulaceae",
    category: "Succulents",
    description: "Popular succulent with clusters of cheerful flowers in red, orange, yellow, or pink.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Kalanchoe_blossfeldiana5.jpg/320px-Kalanchoe_blossfeldiana5.jpg",
    careGuide: { water: "Low", sunlight: "Bright Indirect", soil: "Well-drained succulent mix", difficulty: "Very Easy" },
    climate: "Tropical",
    price: "PKR 200–600",
    availability: "Common",
    health: "Ornamental. Traditional wound healing in Madagascar.",
    diseases: ["Root Rot", "Powdery Mildew", "Mealybugs"],
    tags: ["indoor", "succulent", "flowering", "beginner"],
  },
];

async function seedDB() {
  await mongoose.connect(MONGO_URI);
  console.log("Connected to MongoDB");

  await Plant.deleteMany({});
  console.log("Cleared old plants");

  await Plant.insertMany(plants);
  console.log(`✅ Seeded ${plants.length} plants successfully!`);

  mongoose.disconnect();
}

seedDB().catch(console.error);